import { StyleSheet } from "react-native";
import { themas } from "../../global/themes";

export const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: themas.colors.bgScreen,
  },
  header: {
    height: 140,
    backgroundColor: themas.colors.primary,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    elevation: 8,
    position: "relative",
  },
  backButton: {
    position: "absolute",
    left: 20,
    top: 40,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#fff",
    marginTop: 10,
  },
  body: {
    flex: 1,
    padding: 20,
  },
  pacienteCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 4,
  },
  pacienteHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
  },
  avatarContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: themas.colors.bgScreen,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
  },
  infoHeader: {
    flex: 1,
  },
  nome: {
    fontSize: 22,
    fontWeight: "bold",
    color: themas.colors.secondary,
    marginBottom: 5,
  },
  subtitulo: {
    fontSize: 15,
    color: "#666",
  },
  divider: {
    height: 1,
    backgroundColor: "#f0f0f0",
    marginVertical: 15,
  },
  dadosGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  dadoItem: {
    width: "48%",
    alignItems: "center",
    padding: 15,
    backgroundColor: themas.colors.bgScreen,
    borderRadius: 12,
    marginBottom: 10,
  },
  dadoLabel: {
    fontSize: 12,
    color: "#999",
    marginTop: 8,
    marginBottom: 4,
  },
  dadoValor: {
    fontSize: 16,
    fontWeight: "bold",
    color: themas.colors.secondary,
  },
  getDetalhes: {
    marginTop: 10,
  },
  getTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: themas.colors.secondary,
    marginBottom: 12,
  },
  getRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  getTexto: {
    fontSize: 14,
    color: "#666",
    marginLeft: 10,
  },
  dietasHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  dietasTitulo: {
    fontSize: 20,
    fontWeight: "bold",
    color: themas.colors.secondary,
  },
  buttonNovaDieta: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: themas.colors.primary,
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 20,
  },
  buttonNovaDietaText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
    marginLeft: 6,
  },
  loadingContainer: {
    padding: 40,
    alignItems: "center",
  },
  loadingText: {
    marginTop: 15,
    fontSize: 14,
    color: "#666",
  },
  emptyContainer: {
    padding: 40,
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 15,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#666",
    marginTop: 15,
  },
  emptySubtext: {
    fontSize: 14,
    color: "#999",
    marginTop: 8,
    textAlign: "center",
  },
  dietaCard: {
    backgroundColor: "#fff",
    borderRadius: 15,
    overflow: "hidden",
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  dietaHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
  },
  dietaIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: themas.colors.bgScreen,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
  },
  dietaInfo: {
    flex: 1,
  },
  dietaTitulo: {
    fontSize: 16,
    fontWeight: "bold",
    color: themas.colors.secondary,
    marginBottom: 4,
  },
  dietaData: {
    fontSize: 13,
    color: "#666",
    marginBottom: 6,
  },
  statusBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: "#e8f5e9",
  },
  statusText: {
    fontSize: 12,
    color: "#4caf50",
    fontWeight: "600",
  },
  dietasList: {
    gap: 15,
  },
  dietaContent: {
    padding: 15,
    backgroundColor: "#fafafa",
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
  },
  refeicoesTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: themas.colors.secondary,
    marginBottom: 12,
  },
  refeicaoCard: {
    backgroundColor: "#fff",
    borderRadius: 10,
    marginBottom: 12,
    overflow: "hidden",
  },
  refeicaoHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 12,
    backgroundColor: "#fff",
  },
  refeicaoHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    gap: 10,
  },
  refeicaoIcone: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: themas.colors.primary + "15",
    alignItems: "center",
    justifyContent: "center",
  },
  refeicaoNome: {
    fontSize: 15,
    fontWeight: "600",
    color: themas.colors.secondary,
  },
  refeicaoHorario: {
    fontSize: 12,
    color: "#999",
    marginTop: 2,
  },
  alimentosContainer: {
    padding: 12,
    backgroundColor: "#f9f9f9",
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
  },
  alimentosTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#666",
    marginBottom: 10,
  },
  alimentoItem: {
    backgroundColor: "#fff",
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  alimentoHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
    gap: 8,
  },
  alimentoNome: {
    fontSize: 14,
    fontWeight: "500",
    color: themas.colors.secondary,
  },
  alimentoQuantidade: {
    fontSize: 13,
    color: "#666",
    marginLeft: 20,
  },
});
