import { StyleSheet } from "react-native";
import { themas } from "../../global/themes";

export const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: themas.colors.bgScreen,
  },
  header: {
    height: 140,
    backgroundColor: themas.colors.primary,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    elevation: 8,
    position: "relative",
  },
  backButton: {
    position: "absolute",
    left: 20,
    top: 40,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#fff",
    marginTop: 10,
  },
  body: {
    flex: 1,
    padding: 20,
  },
  pacienteCard: {
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    elevation: 3,
  },
  pacienteHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  pacienteNome: {
    fontSize: 20,
    fontWeight: "bold",
    color: themas.colors.secondary,
    marginLeft: 12,
  },
  pacienteInfo: {
    marginTop: 8,
  },
  pacienteDetalhe: {
    fontSize: 14,
    color: "#666",
    marginTop: 4,
  },
  label: {
    fontSize: 16,
    fontWeight: "700",
    color: themas.colors.secondary,
    marginBottom: 8,
  },
  labelSmall: {
    fontSize: 14,
    fontWeight: "600",
    color: "#666",
    marginBottom: 6,
    marginTop: 12,
  },
  inputTitulo: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 15,
    fontSize: 16,
    color: themas.colors.secondary,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: themas.colors.secondary,
    marginBottom: 15,
    marginTop: 10,
  },
  refeicaoCard: {
    backgroundColor: "#fff",
    borderRadius: 15,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    elevation: 2,
    overflow: "hidden",
  },
  refeicaoHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    backgroundColor: themas.colors.bgScreen,
  },
  refeicaoHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  refeicaoNome: {
    fontSize: 16,
    fontWeight: "600",
    color: themas.colors.secondary,
    marginLeft: 12,
  },
  refeicaoBody: {
    padding: 16,
  },
  input: {
    backgroundColor: "#f8f8f8",
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    color: themas.colors.secondary,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    marginBottom: 12,
  },
  alimentoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  buttonAddAlimento: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: themas.colors.primary,
    borderStyle: "dashed",
    marginTop: 8,
  },
  buttonAddAlimentoText: {
    color: themas.colors.primary,
    fontSize: 14,
    fontWeight: "600",
    marginLeft: 8,
  },
  buttonAddRefeicao: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: themas.colors.primary,
    padding: 16,
    borderRadius: 12,
    marginTop: 10,
    marginBottom: 20,
    elevation: 3,
  },
  buttonAddRefeicaoText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 10,
  },
  buttonSalvar: {
    backgroundColor: themas.colors.primary,
    padding: 18,
    borderRadius: 12,
    alignItems: "center",
    elevation: 5,
  },
  buttonDisabled: {
    backgroundColor: "#ccc",
  },
  buttonSalvarText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
  },
});