import { StyleSheet, Platform } from "react-native";
import { themas } from "../../global/themes";

const TRANSLUCENT = "rgba(255,255,255,0.68)";

export const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor:themas.colors.bgScreen,
  },
  headerArea: {
    height: 140,
    backgroundColor:themas.colors.primary,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    elevation: 6,
  },
  headerTitle: {
    fontSize: 42,
    color: themas.colors.secondary,
    fontWeight: "800",
    letterSpacing: 1,
  },
  body: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 28,
  },
  label: {
    marginTop: 12,
    marginLeft: 6,
    color: "#333",
    fontSize: 14,
    fontWeight: "700",
  },
  inputRow: {
    marginTop: 8,
    height: 48,
    backgroundColor: themas.colors.lightGray,
    borderRadius: 28,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.06)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    elevation: 2,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: themas.colors.secondary,
    paddingVertical: 4,
  },
  icon: {
    color: "#333",
    opacity: 0.9,
    marginLeft: 10,
  },
  card: {
    marginTop: 24,
    marginHorizontal: 8,
    backgroundColor: "white",
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 20,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.72)",
    shadowColor: themas.colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    elevation: 5,
  },
  cardTitle: {
    fontSize: 13,
    color: "#666",
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  cardResult: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: "800",
    color: "#222",
    textAlign: "center",
  },
  buttonsRow: {
    marginTop: 22,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 14,
  },
  buttonPrimary: {
    flex: 1,
    height: 48,
    backgroundColor: themas.colors.primary,
    borderRadius: 28,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
    shadowColor: themas.colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    elevation: 6,
  },
  buttonPrimaryText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "800",
  },
  buttonSecondary: {
    width: 110,
    height: 48,
    backgroundColor: themas.colors.lightGray,
    borderRadius: 28,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.08)",
  },
  buttonSecondaryText: {
    color: "#444",
    fontSize: 15,
    fontWeight: "700",
  },
});
